### ISSUE TITLE
Does the Earth Project have copyright issues?

### ISSUE THREAD

**Issue by s729917604** [bornacvitanic/OverwatchObjects#1]
Hello, I saw your project on youtube and downloaded him and ran it, it is so beautiful and perfect, it helped me tremendously, now I have a question about that project about the earth, including whether the mapping is copyrighted or not, it is very important to me, looking forward to your reply, 
      thank you again。

**Comment by bornacvitanic** [comment]
Shouldn't be, it's just an image of the world with outlines projected on a sphere. You can make your own image and swap it out.
